# Generated by Django 4.2.1 on 2023-05-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MathGamesApp", "0005_rename_game_abakateam_game_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="abakateam",
            old_name="game_id",
            new_name="game",
        ),
        migrations.RenameField(
            model_name="bonusteam",
            old_name="game_id",
            new_name="game",
        ),
        migrations.RenameField(
            model_name="dominoteam",
            old_name="game_id",
            new_name="game",
        ),
    ]
