# Generated by Django 4.2.1 on 2023-05-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MathGamesApp", "0007_rename_point1_abakateam_point01_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="end_time",
            field=models.IntegerField(default=0),
        ),
    ]
