# Generated by Django 4.2.1 on 2023-05-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MathGamesApp", "0009_remove_game_end_time_game_end_game"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="end_game",
            new_name="end_time",
        ),
    ]
